### ISSUE TITLE
First Tasks

### ISSUE THREAD

**Issue by hoaphamse171730** [QuyTurtle12/SWP391-SE1840#1]
- [x] ERD @hoaphamse171730 
Due to: **22H 10/5**
 
- [x] Requirement  @QuyTurtle12 
Due to: **24H 10/5**

- [x] #2
Due to: **24H 12/5**
- [x] Use Case Diagram 
Due to: **22H 10/5**

**Comment by hthaitai** [comment]
t đã hoàn thành 1 phần figma theo requirement của Quy nhưng cần thêm 1 số nhánh của từng function của từng role. Mọi người có thể xem thử để t có thể thay đổi!
